### ISSUE TITLE
Document KLR usage without tm cli and Tekton

### ISSUE THREAD

**Issue by Hi-Fi** [triggermesh/knative-lambda-runtime#49]
KLR basically builds Docker image using runtime as base image, and puts that as Knative service to cluster.

If stricter security settings are used in cluster, getting Tekton to build images might be a bit annoying and it would be easier to make the build without this automation.

It would be nice to have documentation of 
1. How to build images including Lambda code without Tekton and `tm` (basicly pointing to those Dockerfiles that are in Tekton task).
2. Tekton service manifest

**Comment by Hi-Fi** [comment]
Relates to #16

**Comment by tzununbekov** [comment]
@Hi-Fi hey, please take a look at the new "[Run in Docker](https://github.com/triggermesh/knative-lambda-runtime#run-in-docker)" section of the readme which may answer some of your questions. Let me know if something is not clear about that.

**Comment by Hi-Fi** [comment]
That part seems great. Could that #16 info be also added there, kind of:
> Above can of course also be used to build images to be run at Knative. Deployment manifest to Knative is like: 
```YAML
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-lambda
spec:
  template:
    spec:
      containers:
        - image: <just build and pushed image>
# No _HANDLER env variable needed if set to Dockerfile.
```
